"""Update User

Revision ID: ff8b0152932e
Revises: 6ff297fa5549
Create Date: 2025-11-22 12:19:06.275545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff8b0152932e'
down_revision: Union[str, Sequence[str], None] = '6ff297fa5549'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('user', sa.Column('hashed_password', sa.Text(), nullable=False))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'hashed_password')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
